#docker build -f Dockerfile.container -t akash-container .
#Make a data folder on your machine before running...
#docker run -it -v $(pwd)/data:/data akash-container
FROM debian
RUN apt-get update ; apt-get install -yqq jq dialog
COPY *.sh ./
ENTRYPOINT ["/menu.sh"]
